### ISSUE TITLE
Error while downloading the dataset

### ISSUE THREAD

**Issue by y2jcodebreaker** [ondyari/FaceForensics#106]
While running the script i got following error: urllib.error.URLError: <urlopen error [Errno 61] Connection refused>.

**Comment by tungp55** [comment]
I got this error too

**Comment by lakshmipriya-ragupathi** [comment]
im getting the same error, were you able to fix it ? @y2jcodebreaker

**Comment by Zaif633** [comment]
Hi can you help me on how to download the dataset from the script

**Comment by lakshmipriya-ragupathi** [comment]
> Hi can you help me on how to download the dataset from the script

e.g. python download.py -d all -c c23 /Users/dataset/ --server EU2

sever EU2 works

**Comment by ccharalambous** [comment]
I have tried with all servers but nothing is downloaded. Is this valid still or do we need a new URL?

**Comment by Sangita912224** [comment]
same happen with me even this url not working. if someone have solution plz late me know Downloading dataset: compressed
Traceback (most recent call last):
  File "/content/download_FaceForensics.py", line 167, in <module>
    main()
  File "/content/download_FaceForensics.py", line 152, in main
    filenames = get_filelist(filelist_url)
  File "/content/download_FaceForensics.py", line 26, in get_filelist
    lines = urllib.request.urlopen(filelist_url)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by amaaanmajid** [comment]
pls someone help cant download
