### ISSUE TITLE
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'

### ISSUE THREAD

**Issue by panicwq** [ondyari/FaceForensics#25]
Traceback (most recent call last):
  File "detect_from_video.py", line 239, in <module>
    test_full_image_network(**vars(args))
  File "detect_from_video.py", line 187, in test_full_image_network
    cuda=cuda)
  File "detect_from_video.py", line 95, in predict_with_model
    output = model(preprocessed_image)
  File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Panicwq\FaceForensics-master\classification\network\models.py", line 113, in forward
    x = self.model(x)
  File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 210, in forward
    x = self.features(input)
  File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 172, in features
    x = self.conv1(input)
  File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\ANACONDA\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'

How to solve this problem? Thanks

**Comment by GoharNiazi** [comment]
> Traceback (most recent call last):
> File "detect_from_video.py", line 239, in
> test_full_image_network(**vars(args))
> File "detect_from_video.py", line 187, in test_full_image_network
> cuda=cuda)
> File "detect_from_video.py", line 95, in predict_with_model
> output = model(preprocessed_image)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "D:\Panicwq\FaceForensics-master\classification\network\models.py", line 113, in forward
> x = self.model(x)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 210, in forward
> x = self.features(input)
> File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 172, in features
> x = self.conv1(input)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'
> 
> How to solve this problem? Thanks

Same problem here. Did you find any solution?

**Comment by GoharNiazi** [comment]
> Traceback (most recent call last):
> File "detect_from_video.py", line 239, in
> test_full_image_network(**vars(args))
> File "detect_from_video.py", line 187, in test_full_image_network
> cuda=cuda)
> File "detect_from_video.py", line 95, in predict_with_model
> output = model(preprocessed_image)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "D:\Panicwq\FaceForensics-master\classification\network\models.py", line 113, in forward
> x = self.model(x)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 210, in forward
> x = self.features(input)
> File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 172, in features
> x = self.conv1(input)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\ANACONDA\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'
> 
> How to solve this problem? Thanks

Same problem here. Did you find any solution?

**Comment by panicwq** [comment]
> > 追溯（最近一次通话最近）：
> > test_full_image_network中的文件“ detect_from_video.py”，第239行
> > （** vars（args）），
> > test_full_image_network中的文件“ detect_from_video.py”，第187行，
> > cuda = cuda）
> > 文件“ detect_from_video.py” ，第95行，在predict_with_model 
> > 输出中=模型（预处理图像）
> > 文件“ F：\ ANACONDA \ lib \ site-packages \ torch \ nn \ modules \ module.py”，第489行，在**调用** 
> > 结果中= self.forward（*输入， ** kwargs）
> > 文件“ D：\ Panicwq \ FaceForensics-master \ classification \ network \ models.py”，第113行，向前
> > x = self.model（x）
> > 文件“ F：\ ANACONDA \ lib \ site-packages \火炬\ nn \ modules \ module.py“，第489行，**调用** 
> > 结果= self.forward（* input，** kwargs）
> > 文件“ F：\ ANACONDA \ lib \ site-packages \ pretrainedmodels \ models \ xception.py”，第210行，向前
> > x = self.features（输入）
> > 文件“ F：\ ANACONDA \ lib \ site-packages \ pretrainedmodels \样式
> > x = self.conv1（input）中的models \ xception.py”，行172，**调用** 
> > 结果中的
> > 行489，“ F：\ ANACONDA \ lib \ site-packages \ torch \ nn \ modules \ module.py” = self.forward（* input，** kwargs）
> > 文件“ F：\ ANACONDA \ lib \ site-packages \ torch \ nn \ modules \ conv.py”，第320行，以正向
> > self.padding，self.dilation，self （.groups）
> > RuntimeError：后端CPU的预期对象，但参数[2](https://github.com/ondyari/FaceForensics/issues/2) “权重” 为后端CUDA****[](https://github.com/ondyari/FaceForensics/issues/2)
> > 如何解决这个问题呢？谢谢
> 
> 这里同样的问题。您找到解决方案了吗？

I have found the solution.

Insert two lines of code after line 92.（detect_from_video.py）

**_```
Device = torch. Device ("cuda:0" if torch. Cuda. Is_available () else "CPU ")
Preprocessed_image = preprocessed_image. To (device)
```_**

**Comment by panicwq** [comment]
> > Traceback (most recent call last):
> > File "detect_from_video.py", line 239, in
> > test_full_image_network(**vars(args))
> > File "detect_from_video.py", line 187, in test_full_image_network
> > cuda=cuda)
> > File "detect_from_video.py", line 95, in predict_with_model
> > output = model(preprocessed_image)
> > File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> > result = self.forward(*input, **kwargs)
> > File "D:\Panicwq\FaceForensics-master\classification\network\models.py", line 113, in forward
> > x = self.model(x)
> > File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> > result = self.forward(*input, **kwargs)
> > File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 210, in forward
> > x = self.features(input)
> > File "F:\ANACONDA\lib\site-packages\pretrainedmodels\models\xception.py", line 172, in features
> > x = self.conv1(input)
> > File "F:\ANACONDA\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> > result = self.forward(*input, **kwargs)
> > File "F:\ANACONDA\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
> > self.padding, self.dilation, self.groups)
> > RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'
> > How to solve this problem? Thanks
> 
> Same problem here. Did you find any solution?

I have found the solution.
Insert two lines of code after line 92.(detect_from_video.py)

`Device = torch. Device ("cuda:0" if torch. Cuda. Is_available () else "CPU ")`
`Preprocessed_image = preprocessed_image. To (device)`

You can try it.

**Comment by MohamedHalith10** [comment]
after change.....it shows 
TypeError: 'collections.OrderedDict' object is not callable

**Comment by cba132435** [comment]
> after change.....it shows
> TypeError: 'collections.OrderedDict' object is not callable

did you fix this?

**Comment by dvrkoo** [comment]
did anyone manage to fix this
