### ISSUE TITLE
invalid enumerant error in glReadPixels

### ISSUE THREAD

**Issue by Nerdary** [ondyari/FaceForensics#43]
I follow the instructions to run /FaceSwapKowalski/faceswap.py, but it crashed at glReadPixels like this. I have been search for fixing for a while but made no progess.

> python faceswap.py -i1 my_path1 -i2 my_path2

>N/A% (0 of 2157) |                                                                                                       | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "faceswap.py", line 169, in <module>
    renderedImg = renderer.render(shape3D)
  File "/home/jinzehui/Deepfake/related_work/FaceForensics/FaceForensics/dataset/FaceSwapKowalski/FaceSwap/FaceRendering.py", line 64, in render
    data = glReadPixels(0, 0, self.w, self.h, GL_BGR, GL_UNSIGNED_BYTE)
  File "/home/jinzehui/.local/lib/python2.7/site-packages/OpenGL/GL/images.py", line 371, in glReadPixels
    imageData
  File "/home/jinzehui/.local/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = 'invalid enumerant',
        baseOperation = glReadPixels,
        cArguments = (
                0,
                0,
                640,
                368,
                GL_BGR,
                GL_UNSIGNED_BYTE,
                array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [...,
        )

**Comment by leobryan** [comment]
I've got the same issue, have you solved that? Looking forward to the reply thanks.
