### ISSUE TITLE
Fail to load provided Meso pretrained model.

### ISSUE THREAD

**Issue by Daisy-Zhang** [ondyari/FaceForensics#73]
When I loaded provided `Meso` pretrained model, I got this:

```
Traceback (most recent call last):
  File "detect_from_image.py", line 182, in <module>
    prob = test_full_image_network(image_path, args.model_path, True)
  File "detect_from_image.py", line 129, in test_full_image_network
    model = torch.load(model_path)
  File "/data/***/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/data/***/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'H'.
```
The `Meso` pretrained model is downloaded from provided link in this repo and the `detect_from_image.py` is obtained by modifying original `detect_from_video.py`.

I think this is because the `Pytorch` only supports weight file such as `.pth`, the `.h5` weight file is used in `Caffe` and `Tensorflow`. 
So what should I do to solve this problem? Have some other test shell to use?

Thanks~:)

**Comment by hzhumsc** [comment]
> When I loaded provided `Meso` pretrained model, I got this:
> 
> ```
> Traceback (most recent call last):
>   File "detect_from_image.py", line 182, in <module>
>     prob = test_full_image_network(image_path, args.model_path, True)
>   File "detect_from_image.py", line 129, in test_full_image_network
>     model = torch.load(model_path)
>   File "/data/***/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
>     return _load(f, map_location, pickle_module, **pickle_load_args)
>   File "/data/***/miniconda3/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, 'H'.
> ```
> 
> The `Meso` pretrained model is downloaded from provided link in this repo and the `detect_from_image.py` is obtained by modifying original `detect_from_video.py`.
> 
> I think this is because the `Pytorch` only supports weight file such as `.pth`, the `.h5` weight file is used in `Caffe` and `Tensorflow`. So what should I do to solve this problem? Have some other test shell to use?
> 
> Thanks~:)

Hello, Daisy. I think you can load the pre-trained model here provided by Andreas and go back to the author(Afchar) of Mesonet to use the original evaluation pipeline there.

**Comment by riolys** [comment]
Hello, Daisy.I wonder if you solved this question?I want to use the pre-trained model of face detector but have not found one, can u give some solutions?
